/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ActivityEntitlementResource', 'model/CoreChallengeActivitySettings', 'model/Property', 'model/RewardSetResource', 'model/SelectedSettingResource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ActivityEntitlementResource'), require('./CoreChallengeActivitySettings'), require('./Property'), require('./RewardSetResource'), require('./SelectedSettingResource'));
  } else {
    // Browser globals (root is window)
    if (!root.KnetikCloud) {
      root.KnetikCloud = {};
    }
    root.KnetikCloud.ChallengeActivityResource = factory(root.KnetikCloud.ApiClient, root.KnetikCloud.ActivityEntitlementResource, root.KnetikCloud.CoreChallengeActivitySettings, root.KnetikCloud.Property, root.KnetikCloud.RewardSetResource, root.KnetikCloud.SelectedSettingResource);
  }
}(this, function(ApiClient, ActivityEntitlementResource, CoreChallengeActivitySettings, Property, RewardSetResource, SelectedSettingResource) {
  'use strict';




  /**
   * The ChallengeActivityResource model module.
   * @module model/ChallengeActivityResource
   * @version 3.0.11
   */

  /**
   * Constructs a new <code>ChallengeActivityResource</code>.
   * @alias module:model/ChallengeActivityResource
   * @class
   * @param activityId {Number} The id of the activity
   */
  var exports = function(activityId) {
    var _this = this;

    _this['activity_id'] = activityId;








  };

  /**
   * Constructs a <code>ChallengeActivityResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChallengeActivityResource} obj Optional instance to populate.
   * @return {module:model/ChallengeActivityResource} The populated <code>ChallengeActivityResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('activity_id')) {
        obj['activity_id'] = ApiClient.convertToType(data['activity_id'], 'Number');
      }
      if (data.hasOwnProperty('additional_properties')) {
        obj['additional_properties'] = ApiClient.convertToType(data['additional_properties'], {'String': Property});
      }
      if (data.hasOwnProperty('challenge_id')) {
        obj['challenge_id'] = ApiClient.convertToType(data['challenge_id'], 'Number');
      }
      if (data.hasOwnProperty('core_settings')) {
        obj['core_settings'] = CoreChallengeActivitySettings.constructFromObject(data['core_settings']);
      }
      if (data.hasOwnProperty('entitlement')) {
        obj['entitlement'] = ActivityEntitlementResource.constructFromObject(data['entitlement']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('reward_set')) {
        obj['reward_set'] = RewardSetResource.constructFromObject(data['reward_set']);
      }
      if (data.hasOwnProperty('settings')) {
        obj['settings'] = ApiClient.convertToType(data['settings'], [SelectedSettingResource]);
      }
      if (data.hasOwnProperty('template')) {
        obj['template'] = ApiClient.convertToType(data['template'], 'String');
      }
    }
    return obj;
  }

  exports.registerChild = function(child, discriminatorValue) {
	  child.discriminatorField = exports.discriminatorField;
	  child.discriminatorValue = discriminatorValue;
	  child.parent = exports;
	  if(exports.children == null)
		  exports.children = {};
	  exports.children[discriminatorValue] = child;
	  if(exports.parent != null)
		  exports.parent.registerChild(child, discriminatorValue);
  }
  
  var discriminatorValue = 'ChallengeActivityResource';


  /**
   * The id of the activity
   * @member {Number} activity_id
   */
  exports.prototype['activity_id'] = undefined;
  /**
   * A map of additional properties, keyed on the property name.  Must match the names and types defined in the template for this item type
   * @member {Object.<String, module:model/Property>} additional_properties
   */
  exports.prototype['additional_properties'] = undefined;
  /**
   * The id of the challenge
   * @member {Number} challenge_id
   */
  exports.prototype['challenge_id'] = undefined;
  /**
   * Defines core settings about the activity that affect how it can be created/played by users. Values may be left null to inherit from parent activity.
   * @member {module:model/CoreChallengeActivitySettings} core_settings
   */
  exports.prototype['core_settings'] = undefined;
  /**
   * The entitlement item needed to participate in the activity as part of this event. Null indicates free entry. When creating/updating only id is used. Item must be pre-existing
   * @member {module:model/ActivityEntitlementResource} entitlement
   */
  exports.prototype['entitlement'] = undefined;
  /**
   * The unique ID for this resource
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The rewards to give at the end of each occurence of the activity. When creating/updating only id is used. Reward set must be pre-existing
   * @member {module:model/RewardSetResource} reward_set
   */
  exports.prototype['reward_set'] = undefined;
  /**
   * The list of settings and the select options
   * @member {Array.<module:model/SelectedSettingResource>} settings
   */
  exports.prototype['settings'] = undefined;
  /**
   * A challenge activity template this challenge activity is validated against (private). May be null and no validation of additional_properties will be done
   * @member {String} template
   */
  exports.prototype['template'] = undefined;



  return exports;
}));


