/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KnetikCloud);
  }
}(this, function(expect, KnetikCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KnetikCloud.NotificationsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NotificationsApi', function() {
    describe('createNotificationType', function() {
      it('should call createNotificationType successfully', function(done) {
        //uncomment below and update the code to test createNotificationType
        //instance.createNotificationType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNotificationType', function() {
      it('should call deleteNotificationType successfully', function(done) {
        //uncomment below and update the code to test deleteNotificationType
        //instance.deleteNotificationType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNotificationType', function() {
      it('should call getNotificationType successfully', function(done) {
        //uncomment below and update the code to test getNotificationType
        //instance.getNotificationType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNotificationTypes', function() {
      it('should call getNotificationTypes successfully', function(done) {
        //uncomment below and update the code to test getNotificationTypes
        //instance.getNotificationTypes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserNotificationInfo', function() {
      it('should call getUserNotificationInfo successfully', function(done) {
        //uncomment below and update the code to test getUserNotificationInfo
        //instance.getUserNotificationInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserNotificationInfoList', function() {
      it('should call getUserNotificationInfoList successfully', function(done) {
        //uncomment below and update the code to test getUserNotificationInfoList
        //instance.getUserNotificationInfoList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserNotifications', function() {
      it('should call getUserNotifications successfully', function(done) {
        //uncomment below and update the code to test getUserNotifications
        //instance.getUserNotifications(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendNotification', function() {
      it('should call sendNotification successfully', function(done) {
        //uncomment below and update the code to test sendNotification
        //instance.sendNotification(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setUserNotificationStatus', function() {
      it('should call setUserNotificationStatus successfully', function(done) {
        //uncomment below and update the code to test setUserNotificationStatus
        //instance.setUserNotificationStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('silenceDirectNotifications', function() {
      it('should call silenceDirectNotifications successfully', function(done) {
        //uncomment below and update the code to test silenceDirectNotifications
        //instance.silenceDirectNotifications(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateNotificationType', function() {
      it('should call updateNotificationType successfully', function(done) {
        //uncomment below and update the code to test updateNotificationType
        //instance.updateNotificationType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
